{% set name = "libunwind" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.savannah.nongnu.org/releases/libunwind/libunwind-{{ version }}.tar.gz
  sha256: 90337653d92d4a13de590781371c604f9031cdb50520366aa1e3a91e1efb1017 
  patches:
    - patches/lib64.patch

build:
  number: 0
  run_exports:
    # breaks backwards compatibility sometimes but we trust the maintainers that they were only internal
    # https://abi-laboratory.pro/index.php?view=timeline&l=libunwind
    - {{ pin_subpackage('libunwind', max_pin='x') }}
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - gnuconfig
  host:

test:
  commands:
    - test -f "${PREFIX}/lib/libunwind.so"
    - test ! -f "${PREFIX}/lib/libunwind.a"
    - test -f "${PREFIX}/include/libunwind.h"
    - test -f "${PREFIX}/include/unwind.h"

about:
  home: http://www.nongnu.org/libunwind
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Defines a portable and efficient C programming interface (API) to determine the call-chain of a program'

extra:
  recipe-maintainers:
    - synapticarbors
    - xhochy
    - matthiasdiener
