{% set name = "libunwind" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.savannah.nongnu.org/releases/libunwind/libunwind-{{ version }}.tar.gz
  sha256: 7194c20dda841b26917c0579e6467b53f7ad2e3f9452e5c77f3c3829c4656b70

build:
  number: 1
  run_exports:
    # breaks backwards compatibility sometimes
    # https://abi-laboratory.pro/index.php?view=timeline&l=libunwind
    - {{ pin_subpackage('libunwind', max_pin='x.x') }}
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
  host:

test:
  commands:
    - test -f "${PREFIX}/lib/libunwind.so"
    - test ! -f "${PREFIX}/lib/libunwind.a"
    - test -f "${PREFIX}/include/libunwind.h"
    - test -f "${PREFIX}/include/unwind.h"

about:
  home: http://www.nongnu.org/libunwind
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Defines a portable and efficient C programming interface (API) to determine the call-chain of a program
  dev_url: https://github.com/libunwind/libunwind
  doc_url: http://www.nongnu.org/libunwind/docs.html

extra:
  recipe-maintainers:
    - synapticarbors
    - xhochy
    - matthiasdiener
